server {
    listen 80;
    server_name p.evpmerch.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/preview-acme;
        default_type text/plain;
    }

    location / {
        return 404;
    }
}
