<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>VanyaTools.Updater</AssemblyName>
    <Version>1.0.24</Version>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
